name: "Approved by"
description: 'Adds "Approved by" to PR description'

inputs:
  GITHUB_TOKEN:
    description: "Github token"
    default: ${{ github.token }}
    required: false

runs:
  using: "node24"
  main: "dist/index.js"
