version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: "Europe/Vilnius"
    open-pull-requests-limit: 10
    versioning-strategy: increase
